<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EntitiesTableSeeder extends Seeder
{
    public function run()
    {
        $entities = [
            [
                'name' => 'AGENCIA DE DESARROLLO RURAL ( ADR )',
                'nemo' => 'ADR',
                'cnitpagador' => '900948958',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AGENCIA DE RENOVACION DEL TERRITORIO ANTIGUA CONSOLIDACION ( ART )',
                'nemo' => 'ART',
                'cnitpagador' => '901006886',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AGENCIA DEL INSPECTOR GENERAL DE TRIBUTOS (ITRC)',
                'nemo' => 'ITRC',
                'cnitpagador' => '900528648',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AGENCIA NACIONAL DE DEFENSA JURÍDICA ( ANDJE )',
                'nemo' => 'ANJ',
                'cnitpagador' => '900507741',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AGENCIA NACIONAL DE HIDROCARBUROS (ANH )',
                'nemo' => 'ANH',
                'cnitpagador' => '830127607',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AGENCIA NACIONAL DE INFRAESTRUCTURA ( ANI )',
                'nemo' => 'ANI',
                'cnitpagador' => '830125996',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AGENCIA NACIONAL DE MINERIA ( ANM )',
                'nemo' => 'ANM',
                'cnitpagador' => '900500018',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AGENCIA NACIONAL DE SEGURIDAD VIAL ( ANSV )',
                'nemo' => 'ANS',
                'cnitpagador' => '900852998',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AGENCIA NACIONAL DE TIERRAS ( ANT )',
                'nemo' => 'ANT',
                'cnitpagador' => '900948953',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDIA ARMENIA',
                'nemo' => 'ADA',
                'cnitpagador' => '890000464',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDIA CALARCA',
                'nemo' => 'ADC',
                'cnitpagador' => '890000441',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDIA NEIVA',
                'nemo' => 'ALCNVA',
                'cnitpagador' => '891180009',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDIA SANTIAGO DE CALI',
                'nemo' => 'ALCSDC',
                'cnitpagador' => '890399011',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AUDITORIA DE COLOMBIA',
                'nemo' => 'AUDI',
                'cnitpagador' => '830065741',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AUTORIDAD NACIONAL DE LICENCIAS AMBIENTALES (ANLA)',
                'nemo' => 'ANLA',
                'cnitpagador' => '900467239',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'BANCO AGRARIO DE COLOMBIA SA',
                'nemo' => 'BCOAGR',
                'cnitpagador' => '800037800',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'BENEFICENCIA DE CUNDINAMARCA',
                'nemo' => 'BDC',
                'cnitpagador' => '899999072',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'BOMBEROS',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '12',
                'status' => 1,
            ],
            [
                'name' => 'CAJA DE VIVIENDA POPULAR',
                'nemo' => 'CDVP',
                'cnitpagador' => '899999074',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'CATASTRO BOGOTA',
                'nemo' => 'CATS',
                'cnitpagador' => '900127768',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'CENTRO DE MEMORIA HISTÓRICA (CNMH)',
                'nemo' => 'CMH',
                'cnitpagador' => '900492141',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'COMISION DE REGULACION DE AGUA POTABLE Y SANEAMIENTO BASICO (CRA)',
                'nemo' => 'APSB',
                'cnitpagador' => '830000212',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'COMISION DE REGULACION DE ENERGIA Y GAS',
                'nemo' => 'CREG',
                'cnitpagador' => '900034993',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'COMISION NACIONAL SERVICIO CIVIL (CNSC)',
                'nemo' => 'CNSC',
                'cnitpagador' => '900003409',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'CONCEJO DE BOGOTA',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '10',
                'status' => 1,
            ],
            [
                'name' => 'CONTRALORIA BOGOTA',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '11',
                'status' => 1,
            ],
            [
                'name' => 'CONTRALORIA DEL TOLIMA',
                'nemo' => 'CONTOL',
                'cnitpagador' => '890706847',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'CONTRALORIA DEPARTAMENTAL QUINDIO',
                'nemo' => 'CDLQ',
                'cnitpagador' => '890003017',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'CONTRALORIA MUNICIPAL ARMENIA',
                'nemo' => 'ADA',
                'cnitpagador' => '890000464',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'CORPORACION AUTONOMA REGIONAL DE CUNDINAMARCA (CAR)',
                'nemo' => 'CAR',
                'cnitpagador' => '899999062',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'DEFENSORIA DEL PUEBLO',
                'nemo' => 'DFP',
                'cnitpagador' => '800186061',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'DEPARTAMENTO DE PROSPERIDAD SOCIAL ( DPS )',
                'nemo' => 'DPS',
                'cnitpagador' => '900039533',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'DEPARTAMENTO DEL SERVICIO CIVIL',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '7',
                'status' => 1,
            ],
            [
                'name' => 'E.S.E HOSPITAL MARIO CORREA RENGIFO',
                'nemo' => 'HMCR',
                'cnitpagador' => '890399047',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'EJERCITO NACIONAL',
                'nemo' => 'EJCOM',
                'cnitpagador' => '800130632',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'EMPRESA DE RENOVACION URBANA ( ERU )',
                'nemo' => 'MTVIV',
                'cnitpagador' => '830144890',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'EMPRESAS PUBLICAS DE CUNDINAMARCA ( EPC )',
                'nemo' => 'EPC',
                'cnitpagador' => '900222346',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ESTASSEGURO ADMINISTRADORA DE BENEFICIOS SAS',
                'nemo' => 'ESTASSEG',
                'cnitpagador' => '901104588',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL ANTIOQUIA',
                'nemo' => 'FGNRNOROCC',
                'cnitpagador' => '800187597',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL ATLANTICO',
                'nemo' => 'FGNRCARIBE',
                'cnitpagador' => '800875568',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL BOGOTA',
                'nemo' => 'FGNREGCENT',
                'cnitpagador' => '800152783',
                'sucursal' => '5',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL BOLIVAR',
                'nemo' => 'FSCTG',
                'cnitpagador' => '800187578',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL BOYACA',
                'nemo' => 'FGNREGCENT',
                'cnitpagador' => '800152783',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CALDAS',
                'nemo' => 'FSMNZ',
                'cnitpagador' => '800187592',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CALI',
                'nemo' => 'FGNREGPACI',
                'cnitpagador' => '800187575',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CAQUETA',
                'nemo' => 'FSFLO',
                'cnitpagador' => '800187591',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CASANARE',
                'nemo' => 'FSCAS',
                'cnitpagador' => '800235720',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CAUCA',
                'nemo' => 'FSPOP',
                'cnitpagador' => '800187621',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CENTRAL',
                'nemo' => 'FGNREGCENT',
                'cnitpagador' => '800152783',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CESAR',
                'nemo' => 'FSVAL',
                'cnitpagador' => '800187644',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CHOCO',
                'nemo' => 'FSQUI',
                'cnitpagador' => '800187624',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CORDOBA',
                'nemo' => 'FSMON',
                'cnitpagador' => '800187606',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL CUNDINAMARCA',
                'nemo' => 'FGNREGCENT',
                'cnitpagador' => '800152783',
                'sucursal' => '3',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL GUAINIA',
                'nemo' => 'FSIGUAI',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL GUAJIRA',
                'nemo' => 'FSRIO',
                'cnitpagador' => '800187626',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL HUILA',
                'nemo' => 'FSNEI',
                'cnitpagador' => '800187609',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL MAGDALENA',
                'nemo' => 'FSSMA',
                'cnitpagador' => '800187632',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL MAGDALENA MEDIA',
                'nemo' => 'FGNRNORORI',
                'cnitpagador' => '900796335',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL META',
                'nemo' => 'FSVIL',
                'cnitpagador' => '800187645',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL NARIÑO',
                'nemo' => 'FSPAS',
                'cnitpagador' => '800187612',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL NORTE DE SANTANDER',
                'nemo' => 'FSCUC',
                'cnitpagador' => '800187589',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL PUTUMAYO',
                'nemo' => 'FSPUT',
                'cnitpagador' => '900796490',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL QUINDIO',
                'nemo' => 'FGNEJECAFE',
                'cnitpagador' => '800187615',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL QUINDIO',
                'nemo' => 'FSARM',
                'cnitpagador' => '800187566',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL RISARALDA',
                'nemo' => 'FGNEJECAFE',
                'cnitpagador' => '800187615',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL SAN ANDRES',
                'nemo' => 'FSAAND',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL SANTANDER',
                'nemo' => 'FGNREGCENT',
                'cnitpagador' => '800152783',
                'sucursal' => '4',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL SANTANDER',
                'nemo' => 'FSBUC',
                'cnitpagador' => '800187569',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL SUCRE',
                'nemo' => 'FSSIN',
                'cnitpagador' => '800187638',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL TOLIMA',
                'nemo' => 'FSIBG',
                'cnitpagador' => '800187590',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FISCALIA SECCIONAL TOLIMA',
                'nemo' => 'FSIBG',
                'cnitpagador' => '800187590',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FONDO DE ADAPTACION',
                'nemo' => 'FA',
                'cnitpagador' => '900450205',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FONDO DE PRESTACIONES ECONOMICAS CESANTIAS Y PENSIONES FONCEP',
                'nemo' => 'FONCEP',
                'cnitpagador' => '830053105',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FONDO DE PRESTACIONES ECONOMICAS CESANTIAS Y PENSIONES FONCEP',
                'nemo' => 'FONCEP',
                'cnitpagador' => '860041163',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FONDO FERROCARRILES (FPS)',
                'nemo' => 'FFC',
                'cnitpagador' => '800112806',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FUNCIONARIO INDEPENDIENTE',
                'nemo' => 'No Aplico',
                'cnitpagador' => 'No Aplico',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FUNDACION GILBERTO ALZATE AVENDAÑO ( FUGA )',
                'nemo' => 'FGAA',
                'cnitpagador' => '860044113',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'FUNDACION UNIVERSITARIA AGRARIA DE COLOMBIA',
                'nemo' => 'FUAGCO',
                'cnitpagador' => '',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'GOBERNACION DE ANTIOQUIA',
                'nemo' => 'GOBANTQ',
                'cnitpagador' => '890900286',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'GOBERNACION DE BOYACA',
                'nemo' => 'GBOY',
                'cnitpagador' => '891800498',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'GOBERNACION DE BOYACA - POSITIVA POLIZA ANTERIOR',
                'nemo' => 'GBOY',
                'cnitpagador' => '891800498',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'GOBERNACION DE CUNDINAMARCA',
                'nemo' => 'GDC',
                'cnitpagador' => '899999114',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'GOBERNACION DE RISARALDA',
                'nemo' => 'GRIS',
                'cnitpagador' => '891480085',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'GOBERNACION DE TOLIMA',
                'nemo' => 'GBT',
                'cnitpagador' => '800113672',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'GOBERNACION DE TOLIMA - SEC DE SALUD',
                'nemo' => 'GBT',
                'cnitpagador' => '800113672',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'GOBERNACION DEL HUILA',
                'nemo' => 'GOBHUI',
                'cnitpagador' => '800103913',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'GOBERNACION DEL QUINDIO',
                'nemo' => 'GDLQ',
                'cnitpagador' => '890001639',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INDEPORTES DEL QUINDIO',
                'nemo' => 'INDQ',
                'cnitpagador' => '801001532',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO COLOMBIANO DE ANTROPOLOGIA E HISTORIA ( ICANH )',
                'nemo' => 'ICANH',
                'cnitpagador' => '830067892',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO DE HIDROLOGIA METEOROLOGIA Y ESTUDIOS AMBIENTALES ( IDEAM )',
                'nemo' => 'IDAM',
                'cnitpagador' => '830000602',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO DEPARTAMENTAL DE ACCION COMUNAL DE CUNDINAMARCA (IDACCO)',
                'nemo' => 'IDDAC',
                'cnitpagador' => '900294898',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO DISTRITAL DE LA PARTICIPACION Y ACCION COMUNAL ( IDPAC )',
                'nemo' => 'IDPAC',
                'cnitpagador' => '900127054',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO DISTRITAL DE LAS ARTES ( IDARTES )',
                'nemo' => 'IDI',
                'cnitpagador' => '900413030',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO DISTRITAL DE PATRIMONIO CULTURAL ( IDPC )',
                'nemo' => 'IDPC',
                'cnitpagador' => '860506170',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO DISTRITAL DE RECREACION Y DEPORTE ( IDRD )',
                'nemo' => 'IDRD',
                'cnitpagador' => '860061099',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO DISTRITAL DE TURISMO ( IDT )',
                'nemo' => 'IDDT',
                'cnitpagador' => '900140515',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO DISTRITAL PARA LA PROTECCION DE LA NIÑEZ Y JUVENTUD ( IDIPRON )',
                'nemo' => 'IDPR',
                'cnitpagador' => '899999333',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'INSTITUTO NACIONAL SALUD',
                'nemo' => 'INNASAL',
                'cnitpagador' => '899999403',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'JUNTA CENTRAL DE CONTADORES (JCC)',
                'nemo' => 'JCC',
                'cnitpagador' => '900180739',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DE AGRICULTURA Y DESARROLLO RURAL',
                'nemo' => 'AGR',
                'cnitpagador' => '899999028',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DE CULTURA',
                'nemo' => 'MRDC',
                'cnitpagador' => '830034348',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DE DEFENSA',
                'nemo' => 'MDDF',
                'cnitpagador' => '899999003',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DE HACIENDA Y CREDITO PUBLICO (MHCP)',
                'nemo' => 'MHCP',
                'cnitpagador' => '899999090',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DE MINAS Y ENERGIA',
                'nemo' => 'MDMS',
                'cnitpagador' => '899999022',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DE SALUD',
                'nemo' => 'MNS',
                'cnitpagador' => '900474727',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DE TRABAJO',
                'nemo' => 'MTR',
                'cnitpagador' => '830115226',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DE TRANSPORTE',
                'nemo' => 'MDTRS',
                'cnitpagador' => '899999055',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DE VIVIENDA',
                'nemo' => 'MNVIV',
                'cnitpagador' => '900463725',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DEL DEPORTE - COLDEPORTES',
                'nemo' => 'CLDP',
                'cnitpagador' => '899999306',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DEL INTERIOR',
                'nemo' => 'MININTER',
                'cnitpagador' => '830114475',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'MINISTERIO DEL MEDIO AMBIENTE',
                'nemo' => 'MTA',
                'cnitpagador' => '830115395',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'PERSONERIA BOGOTA',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '14',
                'status' => 1,
            ],
            [
                'name' => 'PERSONERIA MUNICIPAL ARMENIA',
                'nemo' => 'PME',
                'cnitpagador' => '800252796',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'POLICIA NACIONAL DIRECCION ADMINISTRATIVA Y FINANCIERA',
                'nemo' => 'POADM',
                'cnitpagador' => '800141397',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'POSITIVA',
                'nemo' => 'PTVA',
                'cnitpagador' => '860011153',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'PROCURADURIA',
                'nemo' => 'PRCU',
                'cnitpagador' => '899999119',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RADIO TELEVISION NACIONAL DE COLOMBIA',
                'nemo' => 'RTVC',
                'cnitpagador' => '900002583',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL ( CENDOJ )',
                'nemo' => 'RGCB',
                'cnitpagador' => '800093816',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL ( DEAJ )',
                'nemo' => 'RGCB',
                'cnitpagador' => '800093816',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL ARMENIA',
                'nemo' => 'RAARM',
                'cnitpagador' => '800165939',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL BARRANQUILLA',
                'nemo' => 'RABAQ',
                'cnitpagador' => '800165799',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL BUCARAMANGA',
                'nemo' => 'RABUC',
                'cnitpagador' => '800165941',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL CALI',
                'nemo' => 'RACAL',
                'cnitpagador' => '805003838',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL CARTAGENA',
                'nemo' => 'RACAR',
                'cnitpagador' => '800165831',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL CUCUTA',
                'nemo' => 'RACUC',
                'cnitpagador' => '800165874',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL IBAGUE',
                'nemo' => 'RAIBG',
                'cnitpagador' => '800165945',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL MANIZALES',
                'nemo' => 'RACALD',
                'cnitpagador' => '800165850',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL MEDELLIN',
                'nemo' => 'RAMED',
                'cnitpagador' => '800165798',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL MONTERIA',
                'nemo' => 'RAMON',
                'cnitpagador' => '800165860',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL NEIVA',
                'nemo' => 'RANEI',
                'cnitpagador' => '800165866',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL PASTO',
                'nemo' => 'RAPAS',
                'cnitpagador' => '800165872',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL PEREIRA',
                'nemo' => 'RJPE',
                'cnitpagador' => '800165940',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL POPAYAN',
                'nemo' => 'RAPOP',
                'cnitpagador' => '800165853',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL QUIBDO',
                'nemo' => 'RAQUIB',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL RIOHACHA',
                'nemo' => 'RARIO',
                'cnitpagador' => '800165865',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL SANTA MARTA',
                'nemo' => 'RAMAG',
                'cnitpagador' => '800165868',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL SINCELEJO',
                'nemo' => 'RASIN',
                'cnitpagador' => '800165944',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL TUNJA',
                'nemo' => 'RATUN',
                'cnitpagador' => '800165804',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL VALLEDUPAR',
                'nemo' => 'RAVAL',
                'cnitpagador' => '800165854',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL VILLAVICENCIO',
                'nemo' => 'RAVIL',
                'cnitpagador' => '822001228',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'RAMA JUDICIAL SECCIONAL YOPAL',
                'nemo' => 'RAYOP',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - ANTIOQUIA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '15',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - ARAUCA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - ATLANTICO',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '16',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - BOGOTA D.C.',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '17',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - BOLIVAR',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - BOYACA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '18',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - CALDAS',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '3',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - CAUCA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '19',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - CESAR',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '4',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - CHOCO',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '20',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - CORDOBA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '21',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - CUNDINAMARCA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '5',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - GUAINIA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '22',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - GUAVIARE',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '6',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - HUILA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '23',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - LA GUAJIRA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '7',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - MAGDALENA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '24',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - META',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '8',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - NARIÑO',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '25',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - NORTE DE SANTANDER',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '9',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - PUTUMAYO',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '26',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - QUINDIO',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '10',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - RISARALDA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '27',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - SANTANDER',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '28',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - SUCRE',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '11',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - TOLIMA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '12',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - VALLE DEL CAUCA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '29',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - VAUPES',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '13',
                'status' => 1,
            ],
            [
                'name' => 'REGISTRADURIA NACIONAL DEL ESTADO CIVIL - VICHADA',
                'nemo' => 'RNEC',
                'cnitpagador' => '899999040',
                'sucursal' => '14',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DE DESARROLLO ECONOMICO',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DE EDUCACION DEPARTAMENTAL DE BOYACA(SED)',
                'nemo' => 'GBOY',
                'cnitpagador' => '891800498',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DE EDUCACION DEPARTAMENTAL DEL HUILA (SED)',
                'nemo' => 'SEDHUI',
                'cnitpagador' => '800103913',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DE EDUCACION DEPARTAMENTAL DEL QUINDIO (SED)',
                'nemo' => 'GDLQ',
                'cnitpagador' => '890001639',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DE EDUCACION DEPARTAMENTAL DEL TOLIMA (SED)',
                'nemo' => 'GBT',
                'cnitpagador' => '800113672',
                'sucursal' => '3',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DE EDUCACION MUNICIPAL ARMENIA',
                'nemo' => 'SEMARM',
                'cnitpagador' => '890000464',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DE INTEGRACION SOCIAL (SDIS)',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '3',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DEL HABITAT',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '4',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DISTRITAL DE GOBIERNO',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '15',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DISTRITAL DE HACIENDA (SHD)',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '5',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DISTRITAL DE LA MUJER',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '18',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DISTRITAL DE MOVILIDAD',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '17',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DISTRITAL DE PLANEACION (SDP)',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '6',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA DISTRITAL DE SEGURIDAD, CONVIVENCIA Y JUSTICIA ( SCJ )',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '9',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA GENERAL ALCALDIA MAYOR DE BOGOTA',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'SECRETARIA JURIDICA DISTRITAL',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '13',
                'status' => 1,
            ],
            [
                'name' => 'SENADO DE LA REPUBLICA',
                'nemo' => 'SNAD',
                'cnitpagador' => '899999103',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'SERVICIO NACIONAL DE APRENDIZAJE',
                'nemo' => 'SENA',
                'cnitpagador' => '899999034',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'SUPERINTENDENCIA DE INDUSTRIA Y COMERCIO ( SIC )',
                'nemo' => 'SIC',
                'cnitpagador' => '800176089',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'SUPERINTENDENCIA DE SERVICIOS PUBLICOS ( SSP )',
                'nemo' => 'SISP',
                'cnitpagador' => '800250984',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'SUPERINTENDENCIA DE SUBSIDIO FAMILIAR ( SSF )',
                'nemo' => 'SIDSF',
                'cnitpagador' => '860503600',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'SUPERINTENDENCIA ECONOMICA SUPERSOLIDARIA',
                'nemo' => 'SSL',
                'cnitpagador' => '830053043',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'UNIDAD ADMINISTRATIVA ESPECIAL DEL SERVICIO PUBLICO DEL EMPLEO',
                'nemo' => 'UAESPE',
                'cnitpagador' => '890303797',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'UNIDAD DE SERVICIOS PENITENCIARIOS Y CARCELARIOS ( USPEC )',
                'nemo' => 'USPEC',
                'cnitpagador' => '900523392',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'UNIDAD NACIONAL DE PROTECCION (UNP)',
                'nemo' => 'UNP',
                'cnitpagador' => '900475780',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'UNIVERSIDAD DISTRITAL FRANCISCO JOSE DE CALDAS',
                'nemo' => 'UNFRAC',
                'cnitpagador' => '899999230',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'UNIVERSIDAD NACIONAL DE COLOMBIA',
                'nemo' => 'UNALC',
                'cnitpagador' => '899999063',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'UNIVERSIDAD NACIONAL DE COLOMBIA - BOGOTA',
                'nemo' => 'UNALCB',
                'cnitpagador' => '899999063',
                'sucursal' => '2',
                'status' => 1,
            ],
            [
                'name' => 'VEEDURIA DISTRITAL DE BOGOTA',
                'nemo' => 'SGRL',
                'cnitpagador' => '899999061',
                'sucursal' => '8',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDIA DE SALINA',
                'nemo' => 'ALCSLN',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDÍA DE GUALMATÁN',
                'nemo' => 'ALCGLM',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDÍA DE ALBÁN CUNDINAMARCA',
                'nemo' => 'ALCLBN',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDÍA DE GÜEPSA - SANTANDER',
                'nemo' => 'ALCGPS',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'AGENCIA DE RENOVACIÓN DEL TERRITORIO',
                'nemo' => 'AGNRNV',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDÍA DE EL MOLINO',
                'nemo' => 'ALCMOLN',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDÍA DE VENECIA - CUNDINAMARCA',
                'nemo' => 'ALCVNC',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDÍA DE TIBASOSA',
                'nemo' => 'ALCTBS',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'EMPRESA SOCIAL DEL ESTADO TIERRADENTRO',
                'nemo' => 'ESET',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDÍA DE SUTATAUSA',
                'nemo' => 'ALCSTT',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'EMSERVILLA ESP',
                'nemo' => 'EMSE',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDÍA DE VIANÍ',
                'nemo' => 'ALCVNI',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'ALCALDÍA DE MONGUA',
                'nemo' => 'ALCMNG',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
            [
                'name' => 'TERMINAL DE TRANSPORTE S.A.',
                'nemo' => 'TRMTRANS',
                'cnitpagador' => '0',
                'sucursal' => '1',
                'status' => 1,
            ],
        ];

        DB::table('entities')->insert($entities);
    }
}
